actions: Add global tests suite for golang with coverage

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -11,4 +11,36 @@ jobs:
       with:
         go-version: '1.17'
         check-latest: true
-    - run : echo "🎉"
+    - name: Setup GO environment
+      run: |
+        go mod download
+        go get -u golang.org/x/lint/golint
+        go get -t .
+    - name: Run Go Lint
+      run: |
+        golint -set_exit_status ./...
+    - name: Run Go vet
+      run: |
+        go vet ./...
+    - name: Run Unit tests
+      run: |
+        go test ./... -coverprofile coverage.out -covermode count
+        go tool cover -func coverage.out
+    - name: Quality Gate - Test coverage shall be above threshold
+      env:
+          TESTCOVERAGE_THRESHOLD: 90
+      run: |
+        echo "Quality Gate: checking test coverage is above threshold ..."
+        echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+        totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+        echo "Current test coverage : $totalCoverage %"
+        if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+            echo "OK"
+        else
+            echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+            echo "Failed"
+            exit 1
+        fi
+    - name: Run Go Build
+      run: |
+        go build -o /tmp/applications-test-units
